@startuml

actor User
participant Symulacja
participant Plansza
participant Mysz
participant Kot
participant Ser

User -> Symulacja: Start simulation with params
Symulacja -> Plansza: Create(szerokosc, wysokosc, myszy, koty)
Plansza -> Norka: Create norek
Plansza -> Mysz: Create myszy
Plansza -> Kot: Create kotów
Plansza -> Ser: Create serów

loop while myszy alive and koty alive
  Symulacja -> Plansza: symulujKrok()
  Plansza -> Mysz: poruszajSie()
  Plansza -> Kot: poruszajSie()
  Plansza -> Kot: zjedzMysz() if same position
  Plansza -> Mysz: zjedzSer() if same position
  Symulacja -> Plansza: wyswietlPlansze()
end

Symulacja -> User: Simulation results

@enduml