@startuml

object plansza {
    szerokosc = 10
    wysokosc = 10
    liczbaZywychMyszy = 5
    koty = new ArrayList<>()
    myszy = new ArrayList<>()
    norki = new ArrayList<>()
    sery = new ArrayList<>()
    random = new Random()
}

object norka1 {
    x = 2
    y = 3
}

object norka2 {
    x = 8
    y = 7
}

object mysz1 {
    x = 4
    y = 6
    aktywna = true
    energia = 10
}

object mysz2 {
    x = 1
    y = 8
    aktywna = true
    energia = 8
}

object mysz3 {
    x = 6
    y = 2
    aktywna = true
    energia = 10
}

object ser1 {
    x = 5
    y = 3
}

object ser2 {
    x = 7
    y = 4
}

object kot1 {
    x = 2
    y = 5
    energia = 20
}

object kot2 {
    x = 6
    y = 8
    energia = 15
}

' Kolekcje
plansza "1" *-- "norki" norka1
plansza "1" *-- "norki" norka2
plansza "1" *-- "myszy" mysz1
plansza "1" *-- "myszy" mysz2
plansza "1" *-- "myszy" mysz3
plansza "1" *-- "sery" ser1
plansza "1" *-- "sery" ser2
plansza "1" *-- "koty" kot1
plansza "1" *-- "koty" kot2

@enduml