@startuml
state "W norce" as W_norce
state "Aktywna" as Aktywna
state "Zjadła ser" as Zjadla_ser
state "Nieaktywna" as Nieaktywna

W_norce --> Aktywna : Wykonaj ruch
Aktywna --> Zjadla_ser : Najedź na Ser
Aktywna --> Nieaktywna : energia <= 0
Zjadla_ser --> Aktywna : Wykonaj ruch
Zjadla_ser --> Nieaktywna : energia <= 0

@enduml