@startuml

[*] --> Nieaktywna
Nieaktywna --> Aktywna : poruszajSie()
Nieaktywna --> [*] : energia <= 0
Aktywna --> [*] : kot na tym samym polu
Aktywna --> [*] : energia <= 0
Aktywna --> Aktywna : zjedzSer()\n(energia += 10)

@enduml