@startuml
[*] --> Nieaktywna : nowa mysz\n(energia = MAX_ENERGIA)
Nieaktywna --> Aktywna : ustawAktywna(true)
Aktywna --> Aktywna : poruszajSie()\n(energia--)
Aktywna --> Aktywna : zjedzSer()\n(energia = MAX_ENERGIA)
Aktywna --> [*] : energia <= 0
Aktywna --> [*] : zjedzenie przez kota
@enduml