@startuml

object plansza {
    szerokosc = 10
    wysokosc = 10
    liczbaZywychMyszy = 3
    koty = [kot1, kot2]
    myszy = [mysz1, mysz2, mysz3]
    norki = [norka1, norka2, norka3]
    sery = [ser1, ser2, ser3]
    random = new Random()
}

object norka1 {
    x = 2
    y = 3
}

object norka2 {
    x = 8
    y = 7
}
object norka2 {
    x = 9
    y = 9
}

object mysz1 {
    x = 4
    y = 6
    aktywna = true
    energia = 10
}

object mysz2 {
    x = 1
    y = 8
    aktywna = true
    energia = 8
}

object mysz3 {
    x = 9
    y = 9
    aktywna = false
    energia = 10
}

object ser1 {
    x = 5
    y = 3
}

object ser2 {
    x = 7
    y = 4
}

object ser3 {
    x = 3
    y = 6
}

object kot1 {
    x = 2
    y = 5
    energia = 20
}

object kot2 {
    x = 6
    y = 8
    energia = 15
}

' Relacje kompozycji
plansza *-- "norki" norka1
plansza *-- "norki" norka2
plansza *-- "myszy" mysz1
plansza *-- "myszy" mysz2
plansza *-- "myszy" mysz3
plansza *-- "sery" ser1
plansza *-- "sery" ser2
plansza *-- "sery" ser3
plansza *-- "koty" kot1
plansza *-- "koty" kot2

@enduml